[package]
name = "toy_physics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
educe = "0.6.0"
iced = "0.13.1"
minifb = "0.27.0"
rand = "0.8.5"
soa-rs = "0.7.2"
